export { default as InspectionHeader } from './Header';
export { default as InspectionContents } from './Contents';
export { default as Inspection } from './Inspection';
export { default as InspectionPreProduction } from './PreProduction';
export { default as InspectionPacking } from './Packing';
export { default as InspectionMeasurement } from './Measurement';
export { default as InspectionAttachments } from './Attachments';
export { default as InspectionPackingAndLabel } from './PackingAndLabel';
export { default as InspectionSummary } from './Summary';
